### ISSUE TITLE
Issue with Static Meshes

### ISSUE THREAD

**Issue by SonicExe231** [DarklightGames/io_scene_ase#7] opened 2024-10-18 15:03 UTC
Hello.

I have this problem with static meshes where they have those dark shadows on them or the materials aren't showing.
In UE2 Editor they look fine. The original meshes are exported with UE Viewer.

The screenshots are the originals and the Editor made ones

![Screenshot 2024-10-14 01-05-52](https://github.com/user-attachments/assets/4a231bef-9695-47ef-b73f-fc187740b211)
![Screenshot 2024-10-14 00-46-33](https://github.com/user-attachments/assets/1f40aba8-8659-467f-83a8-8fe455383909)
![Screenshot 2024-10-14 01-05-44](https://github.com/user-attachments/assets/19a8abde-5671-4001-b4a9-62d00e4c7d4f)
![Screenshot 2024-10-14 00-47-32](https://github.com/user-attachments/assets/d95bab89-3233-43e7-b6a8-d9a32d5a46ed)

**Comment by cmbasnett** [comment] 2024-11-05 21:31
@SonicExe231 Please send the files you used to export these ASE files. This looks like it's an issue with the exported normals.

**Comment by SonicExe231** [comment] 2024-11-09 07:26
[Static.zip](https://github.com/user-attachments/files/17686401/Static.zip)

**Comment by cmbasnett** [comment] 2024-11-10 02:36
I'm currently away for a couple of weeks so I won't be able to have a look
at this until then.

**Comment by cmbasnett** [comment] 2024-12-19 19:26
What version of the add-on are you using? Preferably take a screenshot of the add-on information in Blender so I can confirm that it is actually the correct add-on as well.

The PSKX files look fine, and when I export them to ASE and import them into the UE2 editor, they also look fine.

**Comment by SonicExe231** [comment] 2024-12-21 15:18
![Екранна снимка (14)](https://github.com/user-attachments/assets/f12008bf-166d-466b-9e66-16da6d046ee5)

**Comment by SonicExe231** [comment] 2024-12-21 17:26
> ![Екранна снимка (14)](https://private-user-images.githubusercontent.com/171499174/397936067-f12008bf-166d-466b-9e66-16da6d046ee5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ4MDIxODksIm5iZiI6MTczNDgwMTg4OSwicGF0aCI6Ii8xNzE0OTkxNzQvMzk3OTM2MDY3LWYxMjAwOGJmLTE2NmQtNDY2Yi05ZTY2LTE2ZGE2ZDA0NmVlNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIyMVQxNzI0NDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lODk2MWUwNWY4MTZjY2JmZGFjNmRkMTc3OTdlOGY1MWYwY2Q4MDc5YjBhMTNmODY3NTlhZTgyYTg1NWRkMzkwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.3qn7zda9NiMFHnO1u1YUoenE8VXDZhFKKYNp2yMQAXg)

The meshes may look normal in the editor, they look fine on my end too, but in-game they look like that.

**Comment by cmbasnett** [comment] 2024-12-23 02:25
@SonicExe231  The version you are using is out of date. I suggest getting the latest version from https://extensions.blender.org/add-ons/io-scene-ase/ and trying again. If the issue persists, please send a .blend file in a state just before the ASE exporter and I can try it on my end to see if there are any issues.

**Comment by SonicExe231** [comment] 2024-12-26 21:07
I replaced the add-on and delete/add the static meshes, but the result is the same.
[O_BK_I_WinCrnr.zip](https://github.com/user-attachments/files/18255441/O_BK_I_WinCrnr.zip)
[Duct2DL.zip](https://github.com/user-attachments/files/18255459/Duct2DL.zip)

**Comment by cmbasnett** [comment] 2024-12-29 11:05
@SonicExe231 This is going to sound dumb but, did you rebuild the lighting on the map? When the static mesh geometry changes, the lighting (i.e., baked vertex coloring) will be invalid and must be rebuilt. I put it in my editor and it seems to light itself fine using UE2.

**Comment by SonicExe231** [comment] 2024-12-29 14:36
@cmbasnett That map cannot be opened in the editor unfortunately. For the lighting I didn't know that. I'm sorry, if I wasted your time on this.
I guess the meshes are fine, even that I used an older version?

**Comment by cmbasnett** [comment] 2024-12-30 11:34
Yea the meshes are fine. Going to close this.

**Closed as not planned by cmbasnett** 2024-12-30 11:34 UTC
Labels: needs more information
